#!/usr/bin/env Rscript
# inline stats behind the [needs stats] claims (manuscript/needs_stats.md)
# reads the figures' aggregated TSVs, writes figs/inline_stats.md verbatim into Results
#   Rscript Inline_statistical_tests.R
# unit of replication = sim replicate (empirical arms = genomic window); per-window
# rows averaged to one value per replicate to avoid pseudoreplication
# expectations:
#   E[pi]     = theta_nom / (1 + (4/3) theta_nom)
#   E[dxy]    = (3/4) (1 - exp(-8 mu T / 3) / (1 + (8/3) theta_nom))
#   E[thetaW] = theta_nom = 4 Ne mu
#   E[FST]    = structured coalescent, alpha = 2  (= 0.237)

suppressPackageStartupMessages({
    library(tidyverse)
})

AGG <- "../analyses/polyploid_multiallele/data/aggregated"
ANL <- "../analyses/polyploid_multiallele/analysis"
BENCH <- "../analyses/benchmark_multicore/data/results/all_cells_long.tsv"
EMP <- "../analyses/empirical-tests/data/aggregated"

# Manuscript simulation parameters (config/sim_params.tsv baseline arms).
Ne <- 1720600
mu <- 5.49e-9
theta_nom <- 4 * Ne * mu                       # 0.0378
E_pi  <- theta_nom / (1 + (4 / 3) * theta_nom)  # 0.0360
E_dxy <- 0.07855381727658725                   # from ploidy_grid_summary.tsv
E_thetaW <- theta_nom
E_fst <- 0.23695960499175686                   # structured coalescent, alpha = 2

ploidy_files <- c(dip = "dip", tet = "tet", hex = "hex", oct = "oct")
ploidy_n     <- c(dip = 2, tet = 4, hex = 6, oct = 8)

# theta-sweep sections (4, 5, 9 = Figure 4) report 2n/8n only (decision 2026-07-15);
# 4n/6n theta arms exist but aren't analysed there. ploidy x missingness sections
# (1, 1b, 2, 2b, 2c = Figure 3) keep all four ploidies. don't collapse the two vectors
theta_ploidy_files <- ploidy_files[c("dip", "oct")]
theta_ploidy_n     <- ploidy_n[c("dip", "oct")]

out <- c()
emit <- function(...) out <<- c(out, sprintf(...))
read_arm <- function(name) {
    f <- file.path(AGG, paste0(name, ".tsv"))
    if (!file.exists(f)) return(NULL)
    suppressWarnings(read_tsv(f, show_col_types = FALSE, progress = FALSE))
}
# mean +/- 95% CI of a vector (t-based), returned as a one-row tibble
ci <- function(x) {
    x <- x[is.finite(x)]
    n <- length(x); m <- mean(x); se <- sd(x) / sqrt(n)
    tibble(mean = m, lo = m - qt(.975, n - 1) * se,
           hi = m + qt(.975, n - 1) * se, n = n)
}
pct <- function(x) sprintf("%+.2f%%", 100 * x)

emit("# Inline statistical tests for pixy 2.x manuscript\n")
emit("_Generated by `figures/Inline_statistical_tests.R`. One section per")
emit("`[needs stats]` flag in `manuscript/needs_stats.md`._\n")
emit("Replicate-level tests unless noted. CI = 95%%.\n")

##########
# 1. ploidy grid: pi and dxy indistinguishable across 2n/4n/6n/8n
##########
emit("\n## 1. Ploidy grid — pi and dxy across 2n/4n/6n/8n\n")
ploidy_grid <- function(prefix, suffix, valcols, Etheory, label) {
    rows <- map_dfr(names(ploidy_files), function(k) {
        d <- read_arm(paste0(prefix, ploidy_files[k], suffix))
        if (is.null(d)) return(NULL)
        # one value per replicate (mean over windows)
        d |>
            group_by(replicate) |>
            summarise(bi = mean(.data[[valcols[1]]], na.rm = TRUE),
                      multi = mean(.data[[valcols[2]]], na.rm = TRUE),
                      .groups = "drop") |>
            mutate(ploidy = ploidy_n[k])
    })
    if (nrow(rows) == 0) { emit("_(no data for %s)_\n", label); return(invisible()) }

    emit("\n**%s.** Per-ploidy means (biallelic / multiallelic-aware), CI on the mean:\n", label)
    emit("\n| ploidy | n | biallelic mean [CI] | %% of E | aware mean [CI] | %% of E |")
    emit("\n|---|---|---|---|---|---|")
    for (p in sort(unique(rows$ploidy))) {
        cb <- ci(rows$bi[rows$ploidy == p]); cm <- ci(rows$multi[rows$ploidy == p])
        emit("\n| %dn | %d | %.4f [%.4f, %.4f] | %.1f%% | %.4f [%.4f, %.4f] | %.1f%% |",
             p, cb$n, cb$mean, cb$lo, cb$hi, 100 * cb$mean / Etheory,
             cm$mean, cm$lo, cm$hi, 100 * cm$mean / Etheory)
    }
    # across-ploidy equivalence on the biallelic estimator
    rng <- range(tapply(rows$bi, rows$ploidy, mean))
    maxdiff <- diff(rng)
    aov_p <- tryCatch(
        anova(lm(bi ~ factor(ploidy), data = rows))[["Pr(>F)"]][1],
        error = function(e) NA)
    emit("\n\nAcross-ploidy spread (biallelic): max pairwise difference in means = %.5f (%.2f%% of E[%s]); one-way ANOVA p = %s. ",
         maxdiff, 100 * maxdiff / Etheory, label, format.pval(aov_p, digits = 2))
    emit("Multiallelic-aware estimator recovers %.0f-%.0f%% of theory across ploidies.\n",
         100 * min(tapply(rows$multi, rows$ploidy, mean)) / Etheory,
         100 * max(tapply(rows$multi, rows$ploidy, mean)) / Etheory)
}
ploidy_grid("pi_",  "_1pop", c("pi_new", "pi_new_multi"),   E_pi,  "pi")
ploidy_grid("dxy_", "_2pop", c("dxy_new", "dxy_new_multi"), E_dxy, "dxy")

##########
# 1b. no regression: new pixy (2.x) reproduces old pixy (0.95.x) on diploid pi/dxy
##########
# pi/dxy are integer ratios (count_diffs / count_comparisons), so old and new give
# bit-identical doubles on identical biallelic all-sites input; only difference is
# old serialising ~17 sig digits vs new's ~15, a <=1-ULP re-parse. verified 2026-07-02
# on one VCF (counts 11856/898440). pooled per-window to expose the tightest residual
emit("\n\n## 1b. No regression vs old pixy (diploid pi & dxy)\n")
regression_check <- function(arm, newcol, oldcol, label) {
    d <- read_arm(arm)
    if (is.null(d) || !all(c(newcol, oldcol) %in% names(d))) {
        emit("\n_(no %s / %s column in %s)_", newcol, oldcol, arm); return(invisible())
    }
    x <- d[[newcol]]; y <- d[[oldcol]]
    ok <- is.finite(x) & is.finite(y)
    x <- x[ok]; y <- y[ok]
    r <- cor(x, y); ad <- abs(x - y)
    emit("\n- **%s** (%d windows): Pearson r = %.12f (1 - r = %.2g); mean|new-old| = %.2g; max|new-old| = %.2g",
         label, length(x), r, 1 - r, mean(ad), max(ad))
}
regression_check("pi_dip_1pop",  "pi_new",     "pi_old",     "pi, 1-pop diploid")
regression_check("dxy_dip_2pop", "dxy_new",    "dxy_old",    "dxy, 2-pop diploid")
regression_check("dxy_dip_2pop", "fst_wc_new", "fst_wc_old", "WC-FST, 2-pop diploid (MAF-0 rerun; float math, not an integer ratio)")
emit("\n\nFor pi and dxy, agreement is at serialization round-trip precision")
emit(" (~1e-16): both statistics are integer ratios, so old pixy 0.95.x and new")
emit(" pixy 2.x produce bit-identical doubles on identical biallelic all-sites")
emit(" input. This is exact reproduction, not a nonzero residual.\n")

##########
# 2. Tajima's D centered near zero at every ploidy x missingness cell
##########
emit("\n\n## 2. Tajima's D = 0 across ploidy x missingness\n")
miss_suffix <- c("0" = "_1pop_tw", "10" = "_1pop_miss10", "25" = "_1pop_miss25",
                 "50" = "_1pop_miss50", "75" = "_1pop_miss75")
dcells <- map_dfr(names(ploidy_files), function(k) {
    map_dfr(names(miss_suffix), function(m) {
        d <- read_arm(paste0("pi_", ploidy_files[k], miss_suffix[m]))
        if (is.null(d) || !"tajimaD_new" %in% names(d)) return(NULL)
        per_rep <- d |> group_by(replicate) |>
            summarise(D = mean(tajimaD_new, na.rm = TRUE), .groups = "drop")
        c <- ci(per_rep$D)
        tibble(ploidy = ploidy_n[k], miss = as.integer(m),
               meanD = c$mean, lo = c$lo, hi = c$hi, n = c$n)
    })
})
if (nrow(dcells)) {
    dcells <- dcells |> mutate(excludes0 = lo > 0 | hi < 0)
    worst <- dcells |> slice_max(abs(meanD), n = 1)
    emit("\n%d ploidy x missingness cells. Biallelic Tajima's D (missingness-aware estimator):\n", nrow(dcells))
    emit("\n- mean D range across cells: [%.3f, %.3f]", min(dcells$meanD), max(dcells$meanD))
    emit("\n- largest-magnitude cell: %dn at %d%% missing, mean D = %.3f [%.3f, %.3f]",
         worst$ploidy, worst$miss, worst$meanD, worst$lo, worst$hi)
    emit("\n- cells whose CI on the mean excludes 0: %d / %d (n = %d replicates each; with this n, |mean D| < ~0.21 throughout is biologically negligible relative to the per-window SD ~1.6)\n",
         sum(dcells$excludes0), nrow(dcells), max(dcells$n))
}

##########
# 2b. Watterson's theta recovers its finite-sites expectation
##########
# compared to finite-sites JC69 (E(s)/a_n biallelic, E(s*)/a_n multi), not nominal
# 4Nmu, as pi/dxy compare to E[pi] = 0.0360 not 0.0378. reads the summary from
# analysis/07_thetaw_tajimaD.R
emit("\n\n## 2b. Watterson's theta vs finite-sites JC69 expectation\n")
tw_sum <- tryCatch(read_tsv(file.path(ANL, "thetaw_tajimaD_summary.tsv"),
                            show_col_types = FALSE, progress = FALSE),
                   error = function(e) NULL)
if (!is.null(tw_sum) && "theoretical" %in% names(tw_sum)) {
    tw <- tw_sum |>
        filter(stat == "thetaw") |>
        mutate(recovery = 100 * mean / theoretical,
               contains_E = ci_lo <= theoretical & ci_hi >= theoretical)
    n_cells <- tw |> filter(estimator == "new") |> nrow()
    emit("\nRecovery = mean estimate / finite-sites JC69 expectation, per (ploidy x")
    emit(" missingness) cell. %d cells per estimator (4 ploidies x missingness 0-75%%).\n", n_cells)
    for (est in c("new", "new_multi")) {
        x <- tw |> filter(estimator == est)
        if (nrow(x) == 0) next
        label <- if (est == "new") "biallelic (missingness-aware)" else "multiallelic-aware"
        emit("\n- %s theta_W: mean %.4f-%.4f; recovers %.1f-%.1f%% of expectation; across-replicate 95%% CI contains E in %d / %d cells",
             label, min(x$mean), max(x$mean), min(x$recovery), max(x$recovery),
             sum(x$contains_E), nrow(x))
    }
    emit("\n")
} else {
    emit("\n_(no thetaw_tajimaD_summary.tsv; run analysis/07_thetaw_tajimaD.R first)_\n")
}

##########
# 2c. Figure 3: estimator bias vs theory across the ploidy x missingness grid
##########
# reported as a simulation study (Morris, White & Crowther 2019), not a
# significance test. quantity of interest is the bias:
#   bias = mean(estimate) - E,   MCSE = SD(estimate)/sqrt(n_sim)
# MCSE shrinks like 1/sqrt(n_sim), so a t-test of "mean == E" mostly measures
# replicate count, not estimator quality. judge accuracy by relative-bias
# magnitude, report MCSE for context.
# Tajima's D special: its "theory" is a neutral simulation
# (analysis/calibrate_neutral_tajimaD.py) with its own MCSE, added in quadrature;
# E ~ 0 so bias is absolute. other four references are exact closed forms (ref MCSE = 0).
# combined ANOVA (below) asks the separate question of whether deviation depends
# on ploidy or missingness
emit("\n\n## 2c. Figure 3 - estimator bias vs theory (Monte Carlo SE)\n")
fig3_stats <- c("pi", "dxy", "fst_hudson", "thetaw", "tajimaD")
fig3_lab   <- c(pi = "pi", dxy = "dxy", fst_hudson = "Hudson FST",
                thetaw = "theta_W", tajimaD = "Tajima's D")
theo <- tryCatch(
    bind_rows(
        read_tsv(file.path(ANL, "missingness_summary.tsv"),
                 show_col_types = FALSE, progress = FALSE) |>
            select(stat, ploidy, miss_pct, estimator, theoretical),
        read_tsv(file.path(ANL, "thetaw_tajimaD_summary.tsv"),
                 show_col_types = FALSE, progress = FALSE) |>
            select(stat, ploidy, miss_pct, estimator, theoretical)),
    error = function(e) NULL)
per_rep <- tryCatch(
    bind_rows(
        read_tsv(file.path(ANL, "per_rep_missingness.tsv"),
                 show_col_types = FALSE, progress = FALSE),
        read_tsv(file.path(ANL, "per_rep_thetaw_tajimaD.tsv"),
                 show_col_types = FALSE, progress = FALSE)),
    error = function(e) NULL)

if (is.null(theo) || is.null(per_rep)) {
    emit("\n_(missing per_rep_*.tsv or *_summary.tsv; run analysis/03 & 07 first)_\n")
} else {
    fig3 <- per_rep |>
        filter(estimator == "new_multi", stat %in% fig3_stats) |>
        left_join(theo, by = c("stat", "ploidy", "miss_pct", "estimator")) |>
        mutate(resid = value - theoretical) |>
        filter(is.finite(resid))
    # Reference Monte Carlo SE. Only Tajima's D has a simulated reference (with
    # its own se_D); the other four references are exact closed forms (ref se = 0).
    ref_se <- tryCatch(
        read_tsv(file.path(ANL, "neutral_tajimaD_reference.tsv"),
                 show_col_types = FALSE, progress = FALSE) |>
            transmute(stat = "tajimaD", ploidy, miss_pct, ref_se = se_D),
        error = function(e) NULL)

    # Per-cell bias and its Monte Carlo SE. bias = mean(estimate) - E; the sim-side
    # MCSE is SD/sqrt(n_sim); for Tajima's D the reference MCSE adds in quadrature.
    cells <- fig3 |>
        group_by(stat, ploidy, miss_pct) |>
        summarise(mean = mean(value), sd = sd(value), n = dplyr::n(),
                  E = first(theoretical), .groups = "drop") |>
        mutate(se_sim = sd / sqrt(n), bias = mean - E, rel_bias = 100 * bias / E)
    if (!is.null(ref_se)) cells <- cells |> left_join(ref_se, by = c("stat", "ploidy", "miss_pct"))
    if (!"ref_se" %in% names(cells)) cells$ref_se <- 0
    cells <- cells |> mutate(ref_se = ifelse(is.na(ref_se), 0, ref_se),
                             mcse = sqrt(se_sim^2 + ref_se^2))

    emit("\nMultiallelic-aware estimator (the one plotted in Figure 3) for pi, dxy, theta_W")
    emit(" and Tajima's D. **Hudson FST is the exception: it is biallelic-only.** These")
    emit(" missingness arms ran before the 2026-07 FST fix, when pixy's FST path re-filtered")
    emit(" to biallelic sites regardless of --include_multiallelic_snps, so the `new_multi`")
    emit(" FST column here holds the biallelic estimand. That is the right target for")
    emit(" Figure 3 regardless -- biallelic FST recovers the coalescent ratio 1 - T_W/T_B,")
    emit(" which is the flat E[FST] tested here -- but 'multiallelic-aware' does not mean")
    emit(" the same thing for FST as for the other four statistics.")
    emit(" bias = mean(estimate)")
    emit(" - E, pooled over the whole grid; MCSE = SD/sqrt(n_sim) is the Monte Carlo")
    emit(" precision of that bias (Morris, White & Crowther 2019), NOT a threshold the")
    emit(" estimator must beat. Accuracy is read off the relative-bias magnitude.")
    emit(" n ~ 72,000 replicates/statistic.\n")
    emit("\n| statistic | N_sim | bias (mean - E) | relative bias | MCSE | worst-cell bias |")
    emit("\n|---|---|---|---|---|---|")
    fig3_summ <- list()
    for (s in fig3_stats) {
        d  <- fig3 |> filter(stat == s)
        cd <- cells |> filter(stat == s)
        if (nrow(d) == 0) next
        near_zero_E <- s == "tajimaD"
        Emean  <- mean(d$theoretical)
        bias   <- mean(d$value) - Emean
        mcse   <- sqrt((sd(d$value) / sqrt(nrow(d)))^2 + mean(cd$ref_se)^2)
        # Tajima's D's expectation is ~0, so bias/E is ill-defined; use the same
        # +1 shift as the combined ANOVA (shift estimate and E by +1 -> the ratio
        # denominator is 1 + E), putting D on the same percentage scale as the rest.
        relb   <- if (near_zero_E) 100 * bias / (1 + Emean) else 100 * bias / abs(Emean)
        max_abs <- max(abs(cd$bias)); max_rel <- max(abs(cd$rel_bias))
        relcol <- if (near_zero_E) sprintf("%+.3f%% (+1 shift)", relb)
                  else sprintf("%+.3f%%", relb)
        maxcol <- if (near_zero_E) sprintf("%.4f abs", max_abs)
                  else sprintf("%.2f%% of E", max_rel)
        emit("\n| %s | %d | %+.2e | %s | %.1e | %s |",
             fig3_lab[s], nrow(d), bias, relcol, mcse, maxcol)
        fig3_summ[[s]] <- tibble(stat = fig3_lab[s], bias = bias, mcse = mcse,
                                 relb = relb, max_abs = max_abs, max_rel = max_rel,
                                 near_zero_E = near_zero_E)
    }
    fs <- bind_rows(fig3_summ)
    prop <- fs |> filter(!near_zero_E)
    emit("\n\nInterpretation (bias magnitude, per Morris et al. 2019):")
    emit("\n- pi, dxy, theta_W, and Hudson FST are unbiased to within %.2f%% of the expected value in every ploidy x missingness cell (pooled relative bias: %s).",
         max(abs(prop$max_rel)),
         paste(sprintf("%s %+.3f%%", prop$stat, prop$relb), collapse = ", "))
    drow <- fs |> filter(near_zero_E)
    if (nrow(drow))
        emit("\n- Tajima's D: pooled bias %+.4f (%+.3f%% under the +1 shift), worst-cell |bias| %.4f (absolute) against its simulated neutral reference; the per-window SD of D is ~1.6, so this is negligible.",
             drow$bias, drow$relb, drow$max_abs)
    emit("\n- MCSE (~1e-5 for pi/dxy/theta_W, ~1e-4 for FST) is the simulation's precision on the bias at this replicate count, not an accuracy bar; the biases above are the reportable quantities.\n")

    # single combined ANOVA: relative deviation ~ statistic x ploidy x missingness
    # (all fixed effects) over all five stats. relative deviation 100 * (est - E) / E
    # puts them on one scale; Tajima's D has E ~ 0 so a raw ratio blows up, apply a
    # +1 shift to both estimate and E (E_D ~ -0.03 -> ~0.97) before the ratio.
    # partitions deviation-from-theory by statistic, ploidy, missingness, interactions
    shift <- c(pi = 0, dxy = 0, fst_hudson = 0, thetaw = 0, tajimaD = 1)
    fig3_rel <- fig3 |>
        mutate(sft = shift[stat],
               rel_dev = 100 * ((value + sft) - (theoretical + sft)) / (theoretical + sft)) |>
        filter(is.finite(rel_dev)) |>
        mutate(statistic = factor(fig3_lab[stat], levels = unname(fig3_lab)),
               ploidy_f  = factor(ploidy),
               miss_f    = factor(miss_pct))
    aov_fit <- aov(rel_dev ~ statistic * ploidy_f * miss_f, data = fig3_rel)
    at <- summary(aov_fit)[[1]]
    ss_tot <- sum(at[["Sum Sq"]])
    terms <- trimws(rownames(at))
    pretty <- terms
    pretty <- gsub("ploidy_f", "ploidy", pretty)
    pretty <- gsub("miss_f", "missingness", pretty)
    pretty <- gsub(":", " x ", pretty)
    emit("\n\n**Combined ANOVA** - relative deviation from theory (%%) ~ statistic x ploidy x")
    emit(" missingness, all fixed effects, one model over all five statistics")
    emit(" (Tajima's D put on the percent scale via a +1 shift of estimate and E).")
    emit(" N = %d replicate estimates.\n", nrow(fig3_rel))
    emit("\n| term | df | F | p | %% of total SS |")
    emit("\n|---|---|---|---|---|")
    for (i in seq_along(terms)) {
        if (pretty[i] == "Residuals") next
        emit("\n| %s | %d | %.2f | %s | %.2f%% |",
             pretty[i], at[["Df"]][i], at[["F value"]][i],
             format.pval(at[["Pr(>F)"]][i], digits = 2),
             100 * at[["Sum Sq"]][i] / ss_tot)
    }
    miss_terms <- grep("missingness", pretty, value = TRUE)
    miss_ss <- sum(at[["Sum Sq"]][pretty %in% miss_terms])
    emit(paste0("\n\nEvery term is a fraction of a percent in effect size. Missingness",
                " (main effect + all interactions involving it) explains %.2f%% of the total",
                " variance in deviation-from-theory and is non-significant; the residual",
                " (replicate sampling noise) is %.1f%%. Ploidy and statistic are significant",
                " but explain a negligible share of the variance: no cell mean departs from",
                " its expectation by more than 0.5%%. (All five statistics share the same n,",
                " so significance here tracks effect size, not replicate count.)\n"),
         100 * miss_ss / ss_tot, 100 * at[["Sum Sq"]][terms == "Residuals"] / ss_tot)
    emit(paste0("\nFootnote on the `statistic` factor: it mixes four multiallelic-aware",
                " statistics (pi, dxy, theta_W, Tajima's D) with one biallelic one (Hudson",
                " FST -- see above). Each is compared against its own correct expectation, so",
                " the deviations are individually interpretable, but the significant",
                " `statistic` term is not an estimator comparison and must not be read as",
                " one.\n"))
}

##########
# 3. missingness x tool interaction on pi (pixy flat, vcftools collapses)
##########
emit("\n\n## 3. Missingness x tool interaction on pi (diploid)\n")
miss3 <- map_dfr(c("10", "25", "50", "75"), function(m) {
    d <- read_arm(paste0("pi_dip_1pop_miss", m))
    if (is.null(d) || !"pi_vcftools" %in% names(d)) return(NULL)
    d |> group_by(replicate) |>
        summarise(pixy = mean(pi_new, na.rm = TRUE),
                  vcftools = mean(pi_vcftools, na.rm = TRUE), .groups = "drop") |>
        mutate(miss = as.numeric(m) / 100)
})
if (nrow(miss3)) {
    long <- miss3 |> pivot_longer(c(pixy, vcftools), names_to = "tool", values_to = "pi")
    m <- lm(pi ~ miss * tool, data = long)
    co <- summary(m)$coefficients
    cf <- confint(m)
    # pixy slope = miss coef; vcftools slope = miss + miss:toolvcftools
    pixy_slope <- co["miss", "Estimate"]
    vcf_slope  <- co["miss", "Estimate"] + co["miss:toolvcftools", "Estimate"]
    emit("\nLinear model pi ~ missingness * tool (slopes per unit = per 100%% missingness):\n")
    emit("\n- pixy slope = %.4f [%.4f, %.4f] (flat)", pixy_slope, cf["miss", 1], cf["miss", 2])
    emit("\n- vcftools slope = %.4f (steep negative)", vcf_slope)
    emit("\n- interaction term miss:tool: estimate %.4f, p = %s\n",
         co["miss:toolvcftools", "Estimate"],
         format.pval(co["miss:toolvcftools", "Pr(>|t|)"], digits = 2))
    vmean <- miss3 |> group_by(miss) |> summarise(v = mean(vcftools), p = mean(pixy))
    emit("\nvcftools pi by missingness: %s. pixy pi: %s.\n",
         paste(sprintf("%.0f%%=%.3f", 100 * vmean$miss, vmean$v), collapse = ", "),
         paste(sprintf("%.0f%%=%.3f", 100 * vmean$miss, vmean$p), collapse = ", "))
}

##########
# 4. multiallelic bias grows with theta; aware estimator near-flat
##########
emit("\n\n## 4. Multiallelic bias vs theta sweep\n")
theta_codes <- c("005" = 0.005, "010" = 0.01, "025" = 0.025, "050" = 0.05, "100" = 0.1)
sweep <- map_dfr(names(theta_ploidy_files), function(k) {
    map_dfr(names(theta_codes), function(tc) {
        d <- read_arm(paste0("pi_", theta_ploidy_files[k], "_1pop_theta", tc))
        if (is.null(d)) return(NULL)
        th <- theta_codes[tc]
        Eth <- th / (1 + (4 / 3) * th)
        d |> group_by(replicate) |>
            summarise(bi = mean(pi_new, na.rm = TRUE),
                      multi = mean(pi_new_multi, na.rm = TRUE), .groups = "drop") |>
            mutate(ploidy = theta_ploidy_n[k], theta = th, Eth = Eth)
    })
})
if (nrow(sweep)) {
    sweep <- sweep |> mutate(bias_bi = (bi - Eth) / Eth, bias_multi = (multi - Eth) / Eth)
    cell_bi <- sweep |> group_by(ploidy, theta) |> summarise(b = mean(bias_bi), .groups = "drop")
    cell_mu <- sweep |> group_by(ploidy, theta) |> summarise(b = mean(bias_multi), .groups = "drop")
    fit <- lm(b ~ theta, data = cell_bi)   # trend of biallelic bias on theta
    cf <- confint(fit)
    emit("\nBiallelic-only bias grows with theta:\n")
    emit("\n- bias range: %s (low theta) to %s (high theta)",
         pct(max(cell_bi$b)), pct(min(cell_bi$b)))
    emit("\n- regression of bias on theta: slope = %.3f [%.3f, %.3f] per unit theta, p = %s (monotone decrease)\n",
         coef(fit)["theta"], cf["theta", 1], cf["theta", 2],
         format.pval(summary(fit)$coefficients["theta", "Pr(>|t|)"], digits = 2))
    cmu <- ci(sweep$bias_multi)
    emit("\nMultiallelic-aware estimator across the whole grid:\n")
    emit("\n- per-cell aware bias range: %s to %s", pct(min(cell_mu$b)), pct(max(cell_mu$b)))
    emit("\n- pooled aware bias: %s [%s, %s] (NOTE: manuscript currently says +/-0.2%%; true bound is ~+/-0.5%%)\n",
         pct(cmu$mean), pct(cmu$lo), pct(cmu$hi))
}

##########
# 5. Hudson FST tracks its estimator-specific expectation
##########
# two expectations, one per estimator: biallelic targets infinite-sites (coalescent)
# E[FST] = 0.237, flat in theta; multi targets finite-sites E[FST](theta), down ~1.6%
# by theta = 0.1. comparing multi against the flat 0.237 (as before 2026-07-15) fakes
# a 1.6% "bias". `theoretical` in the summary is already per-estimator; use it
emit("\n\n## 5. Hudson FST vs its estimator-specific E[FST]\n")
fst_sum <- tryCatch(read_tsv(file.path(ANL, "dxy_fst_theta_summary.tsv"),
                             show_col_types = FALSE, progress = FALSE),
                    error = function(e) NULL)
if (!is.null(fst_sum)) {
    fst <- fst_sum |>
        filter(stat == "fst_hudson", estimator %in% c("new", "new_multi")) |>
        mutate(contains_E = q025 <= theoretical & q975 >= theoretical)
    emit("\nEach estimator against its own expectation, over %d ploidy x theta cells each.",
         nrow(fst) / 2)
    emit(" Biallelic -> infinite-sites E[FST] = %.3f (flat); multiallelic -> finite-sites",
         E_fst)
    emit(" E[FST](theta) (Jukes-Cantor; see analysis/finite_sites_fst_derivation.md).\n")
    for (est in c("new", "new_multi")) {
        x <- fst |> filter(estimator == est)
        if (nrow(x) == 0) next
        lab <- if (est == "new") "biallelic (vs infinite-sites)" else
                                 "multiallelic-aware (vs finite-sites)"
        by_p <- x |> group_by(ploidy) |>
            summarise(maxabs = max(abs(bias_pct)), .groups = "drop")
        emit("\n**%s** — max |bias| by ploidy: %s. Max |bias| over all cells = %.2f%%;",
             lab,
             paste(sprintf("%s %.2f%%", by_p$ploidy, by_p$maxabs), collapse = ", "),
             max(abs(x$bias_pct)))
        emit(" the across-replicate 95%% interval contains E[FST] in %d / %d cells.\n",
             sum(x$contains_E), nrow(x))
    }
    # quote the theta = 0.1 contrast from the data, not hard-coded
    hi <- fst |> filter(theta_nominal == max(theta_nominal))
    hi_bi <- hi |> filter(estimator == "new")
    hi_mu <- hi |> filter(estimator == "new_multi")
    # bootstrap SEs below are from analysis/validate_fst_rerun.py, specific to the
    # 2n/8n cells here (script covers all four ploidies; 4n/6n not carried in)
    emit("\nThe biallelic estimator's residual is the expected one: the filter removes")
    emit(" *visible* homoplasy but back/parallel mutation keeps a site biallelic, so it")
    emit(" sags at high theta -- and significantly so at theta = %.3f (%.2f%% to %.2f%%",
         max(fst$theta_nominal), max(hi_bi$bias_pct), min(hi_bi$bias_pct))
    emit(" depending on ploidy; 3.3 SE at 2n and 7.8 SE at 8n, n = 2000). The")
    emit(" multiallelic estimator shows no such trend against its own expectation: its")
    emit(" worst theta = %.3f deviation is %.2f%% (%s), an order of magnitude smaller.",
         max(fst$theta_nominal), max(abs(hi_mu$bias_pct)),
         hi_mu$ploidy[which.max(abs(hi_mu$bias_pct))])
    emit(" Across all %d cells its largest departure is 1.5 bootstrap SE (octoploid,",
         nrow(hi_mu) * length(unique(fst$theta_nominal)))
    emit(" theta = 0.010), which is what that many cells of replicate noise look like.\n")
}

##########
# 6. multicore scaling power-law exponent
##########
emit("\n\n## 6. Multicore scaling exponent\n")
bench <- tryCatch(read_tsv(BENCH, show_col_types = FALSE, progress = FALSE),
                  error = function(e) NULL)
if (!is.null(bench)) {
    bench <- bench |> mutate(n_cores = as.numeric(n_cores))
    # multicore release = the version present at >1 core count
    multiv <- bench |> filter(status == "OK") |>
        group_by(pixy_version) |> summarise(nc = n_distinct(n_cores)) |>
        slice_max(nc, n = 1) |> pull(pixy_version)
    newv <- bench |> filter(status == "OK", pixy_version == multiv[1])
    med <- newv |> group_by(statistic, n_cores) |>
        summarise(t = median(elapsed_s, na.rm = TRUE), .groups = "drop")
    sp <- med |> group_by(statistic) |>
        mutate(speedup = t[n_cores == 1] / t) |> ungroup()
    emit("\nPower-law fit log(speedup) ~ log(cores) on cores >= 2 (exponent b; speedup = a*cores^b):\n")
    emit("\n| statistic | exponent b [CI] | speedup@16 |")
    emit("\n|---|---|---|")
    for (s in unique(sp$statistic)) {
        d <- sp |> filter(statistic == s, n_cores >= 2)
        if (nrow(d) < 3) next
        f <- lm(log(speedup) ~ log(n_cores), data = d)
        ci_b <- confint(f)["log(n_cores)", ]
        s16 <- sp$speedup[sp$statistic == s & sp$n_cores == 16]
        emit("\n| %s | %.2f [%.2f, %.2f] | %.1fx |", s,
             coef(f)["log(n_cores)"], ci_b[1], ci_b[2],
             ifelse(length(s16), s16, NA))
    }
    emit("\n")
}

##########
# 7 & 8. empirical: paired uplift + bias vs multiallelic density
##########
emit("\n\n## 7-8. Empirical biallelic vs multiallelic-aware\n")
empirical <- function(file, arm) {
    f <- file.path(EMP, file)
    if (!file.exists(f)) { emit("\n_(no data for %s)_\n", arm); return(invisible()) }
    d <- read_tsv(f, show_col_types = FALSE, progress = FALSE)
    pops <- sub("^avg_pi_(.+)_biallelic$", "\\1",
                grep("^avg_pi_.+_biallelic$", names(d), value = TRUE))
    emit("\n**%s** (populations: %s; %d windows):\n", arm, paste(pops, collapse = ", "), nrow(d))
    for (p in pops) {
        bi <- d[[paste0("avg_pi_", p, "_biallelic")]]
        mu_ <- d[[paste0("avg_pi_", p, "_multi")]]
        ok <- is.finite(bi) & is.finite(mu_) & bi > 0
        t <- t.test(mu_[ok], bi[ok], paired = TRUE)
        upl <- (mu_[ok] - bi[ok]) / bi[ok]
        cu <- ci(upl)
        # density proxy = multiallelic snps gained (fst snps multi - biallelic)
        dens <- NULL
        if (all(c("n_snps_fst_multi", "n_snps_fst_biallelic") %in% names(d)))
            dens <- (d$n_snps_fst_multi - d$n_snps_fst_biallelic)[ok]
        emit("\n- pi[%s]: paired mean uplift = %.5f [%.5f, %.5f], p = %s; relative uplift = %s [%s, %s]",
             p, t$estimate, t$conf.int[1], t$conf.int[2],
             format.pval(t$p.value, digits = 2), pct(cu$mean), pct(cu$lo), pct(cu$hi))
        if (!is.null(dens) && sd(dens) > 0) {
            sp <- suppressWarnings(cor.test(upl, dens, method = "spearman"))
            emit("; uplift~density Spearman rho = %.2f, p = %s",
                 unname(sp$estimate), format.pval(sp$p.value, digits = 2))
        }
    }
    emit("\n")
}
empirical("anopheles.joined.tsv", "Anopheles gambiae (2n, chr 3R)")
empirical("arenosa.joined.tsv", "Arabidopsis arenosa (4n, LR999451.1)")

##########
# 9. Figure 4: biallelic-only breaks down as theta (and multiallelic density) rises,
#    multiallelic-aware stays on its finite-sites expectation
##########
# pi/dxy averaged over windows per replicate; E[stat](theta) read from the figure's
# summaries to match the plotted dashed line (E depends on theta only). Hudson FST is
# a ratio of sums, taken from the ratio-correct summary not averaged per-window ratios.
# figure plots 2n/8n; theta trend and its ploidy dependence reported over the full sweep
emit("\n\n## 9. Figure 4 - biallelic breakdown vs multiallelic-aware (theta sweep)\n")
theta_codes4 <- c("005" = 0.005, "010" = 0.01, "025" = 0.025, "050" = 0.05, "100" = 0.1)
pi_sum4   <- tryCatch(read_tsv(file.path(ANL, "multiallelic_frac_summary.tsv"),
                               show_col_types = FALSE, progress = FALSE), error = function(e) NULL)
dxyf_sum4 <- tryCatch(read_tsv(file.path(ANL, "dxy_fst_theta_summary.tsv"),
                               show_col_types = FALSE, progress = FALSE), error = function(e) NULL)
if (is.null(pi_sum4) || is.null(dxyf_sum4)) {
    emit("\n_(missing multiallelic_frac_summary.tsv or dxy_fst_theta_summary.tsv)_\n")
} else {
    Emap <- function(tb) setNames(tb$theoretical, sprintf("%.3f", tb$theta_nominal))
    E_pi_v  <- Emap(distinct(pi_sum4, theta_nominal, theoretical))
    E_dxy_v <- Emap(distinct(filter(dxyf_sum4, stat == "dxy"), theta_nominal, theoretical))
    # FST summary carries two expectations (infinite-sites biallelic, finite-sites
    # multi). here both estimators judged against the same finite-sites E, matching
    # pi/dxy and Figure 4; that common target is what makes the comparison meaningful.
    # section 5 runs the complementary test (each vs its own target).
    # theoretical_fst_finite depends only on theta, so one value per theta
    E_fst_v <- Emap(distinct(filter(dxyf_sum4, stat == "fst_hudson",
                                    estimator == "new_multi"),
                             theta_nominal, theoretical))
    stopifnot(length(E_fst_v) == length(unique(dxyf_sum4$theta_nominal)))

    # per-replicate relative bias (%) across the ploidy x theta sweep
    sweep_rel <- function(prefix, suffix, cols, Ev) {
        map_dfr(names(theta_ploidy_files), function(k) {
            map_dfr(names(theta_codes4), function(tc) {
                d <- read_arm(paste0(prefix, theta_ploidy_files[k], suffix, tc))
                if (is.null(d)) return(NULL)
                th <- unname(theta_codes4[tc]); E <- unname(Ev[sprintf("%.3f", th)])
                d |> group_by(replicate) |>
                    summarise(bi = mean(.data[[cols[1]]], na.rm = TRUE),
                              multi = mean(.data[[cols[2]]], na.rm = TRUE), .groups = "drop") |>
                    mutate(ploidy = theta_ploidy_n[k], theta = th,
                           rbi = 100 * (bi - E) / E, rmu = 100 * (multi - E) / E)
            })
        })
    }

    report_sweep <- function(sw, label) {
        if (nrow(sw) == 0) { emit("\n_(no %s sweep data)_\n", label); return(invisible()) }
        cell_bi <- sw |> group_by(ploidy, theta) |> summarise(b = mean(rbi), .groups = "drop")
        cell_mu <- sw |> group_by(ploidy, theta) |> summarise(b = mean(rmu), .groups = "drop")
        thmin <- min(sw$theta); thmax <- max(sw$theta)
        pls <- sort(unique(cell_bi$ploidy))
        g <- function(tb, pl, th) tb$b[tb$ploidy == pl & abs(tb$theta - th) < 1e-9]
        fit <- lm(b ~ theta, data = cell_bi); cf <- confint(fit)
        w <- which.min(cell_bi$b); cmu <- ci(sw$rmu)
        emit("\n**%s.** Biallelic-only ('new') relative bias vs the finite-sites expectation:\n", label)
        emit("\n- theta = %.3f: %+.2f%% (2n), %+.2f%% (8n) -> theta = %.2f: %+.2f%% (2n), %+.2f%% (8n)",
             thmin, g(cell_bi, 2, thmin), g(cell_bi, 8, thmin),
             thmax, g(cell_bi, 2, thmax), g(cell_bi, 8, thmax))
        emit("\n- worst cell: %+.2f%% (%dn, theta = %.2f)", cell_bi$b[w], cell_bi$ploidy[w], cell_bi$theta[w])
        emit("\n- monotone with theta (all ploidies): OLS slope = %+.1f%% per unit theta [%.1f, %.1f], p = %s",
             coef(fit)["theta"], cf["theta", 1], cf["theta", 2],
             format.pval(summary(fit)$coefficients["theta", "Pr(>|t|)"], digits = 2))
        emit("\n- worsens with ploidy at theta = %.2f: %s", thmax,
             paste(sprintf("%dn %+.1f%%", pls, sapply(pls, function(p) g(cell_bi, p, thmax))), collapse = ", "))
        emit("\n\nMultiallelic-aware ('new_multi') relative bias: pooled %+.2f%% [%+.2f%%, %+.2f%%]; max |cell| = %.2f%% across the whole sweep.\n",
             cmu$mean, cmu$lo, cmu$hi, max(abs(cell_mu$b)))
    }

    pi_sw  <- sweep_rel("pi_",  "_1pop_theta", c("pi_new", "pi_new_multi"),   E_pi_v)
    dxy_sw <- sweep_rel("dxy_", "_2pop_theta", c("dxy_new", "dxy_new_multi"), E_dxy_v)
    report_sweep(pi_sw,  "pi")
    report_sweep(dxy_sw, "dxy")

    # factorial ANOVA of the biallelic deficit: does relative deviation depend on
    # statistic (pi vs dxy), ploidy, theta? theta/ploidy as factors (5 and 4 levels),
    # balanced at 2,000 reps/cell. Figure-4 analogue of the Figure-3 combined ANOVA
    if (nrow(pi_sw) && nrow(dxy_sw)) {
        fig4_bi <- bind_rows(
            pi_sw  |> transmute(statistic = "pi",  ploidy, theta, rel_dev = rbi),
            dxy_sw |> transmute(statistic = "dxy", ploidy, theta, rel_dev = rbi)) |>
            filter(is.finite(rel_dev)) |>
            mutate(statistic = factor(statistic, levels = c("pi", "dxy")),
                   ploidy_f  = factor(ploidy), theta_f = factor(theta))
        aov4 <- aov(rel_dev ~ statistic * ploidy_f * theta_f, data = fig4_bi)
        at4 <- summary(aov4)[[1]]
        ss4 <- sum(at4[["Sum Sq"]]); tn4 <- trimws(rownames(at4))
        pn4 <- gsub("ploidy_f", "ploidy", gsub("theta_f", "theta", gsub(":", " x ", tn4)))
        emit("\n**Biallelic-only deficit - factorial ANOVA** (relative deviation from theory (%%) ~")
        emit(" statistic x ploidy x theta, all factors; N = %d replicate estimates, 2,000 per cell).\n", nrow(fig4_bi))
        emit("\n| term | df | F | p | %% of total SS |")
        emit("\n|---|---|---|---|---|")
        for (i in seq_along(tn4)) {
            if (pn4[i] == "Residuals") next
            emit("\n| %s | %d | %.1f | %s | %.1f%% |",
                 pn4[i], at4[["Df"]][i], at4[["F value"]][i],
                 format.pval(at4[["Pr(>F)"]][i], digits = 2), 100 * at4[["Sum Sq"]][i] / ss4)
        }
        ri <- length(tn4)
        emit("\n| residual | %d | | | %.1f%% |\n", at4[["Df"]][ri], 100 * at4[["Sum Sq"]][ri] / ss4)
    }

    # same ANOVA on the multiallelic-aware estimator: claim is its deviation shows
    # no relationship with theta, ploidy, or statistic. same model and N as the
    # biallelic ANOVA, so F differences reflect effect size not power
    if (nrow(pi_sw) && nrow(dxy_sw)) {
        fig4_mu <- bind_rows(
            pi_sw  |> transmute(statistic = "pi",  ploidy, theta, rel_dev = rmu),
            dxy_sw |> transmute(statistic = "dxy", ploidy, theta, rel_dev = rmu)) |>
            filter(is.finite(rel_dev)) |>
            mutate(statistic = factor(statistic, levels = c("pi", "dxy")),
                   ploidy_f  = factor(ploidy), theta_f = factor(theta))
        aov4m <- aov(rel_dev ~ statistic * ploidy_f * theta_f, data = fig4_mu)
        at4m <- summary(aov4m)[[1]]
        ss4m <- sum(at4m[["Sum Sq"]]); tn4m <- trimws(rownames(at4m))
        pn4m <- gsub("ploidy_f", "ploidy", gsub("theta_f", "theta", gsub(":", " x ", tn4m)))
        emit("\n**Multiallelic-aware estimator - factorial ANOVA** (relative deviation from")
        emit(" theory (%%) ~ statistic x ploidy x theta, all factors; N = %d replicate", nrow(fig4_mu))
        emit(" estimates, 2,000 per cell - identical design and N to the biallelic ANOVA above).\n")
        emit("\n| term | df | F | p | %% of total SS |")
        emit("\n|---|---|---|---|---|")
        for (i in seq_along(tn4m)) {
            if (pn4m[i] == "Residuals") next
            emit("\n| %s | %d | %.2f | %s | %.2f%% |",
                 pn4m[i], at4m[["Df"]][i], at4m[["F value"]][i],
                 format.pval(at4m[["Pr(>F)"]][i], digits = 2), 100 * at4m[["Sum Sq"]][i] / ss4m)
        }
        rim <- length(tn4m)
        emit("\n| residual | %d | | | %.2f%% |\n", at4m[["Df"]][rim], 100 * at4m[["Sum Sq"]][rim] / ss4m)
        nonsig <- sum(at4m[["Pr(>F)"]][-rim] > 0.05, na.rm = TRUE)
        emit("\n%d / %d terms are non-significant at alpha = 0.05; the model explains %.2f%% of the",
             nonsig, rim - 1, 100 * (ss4m - at4m[["Sum Sq"]][rim]) / ss4m)
        emit(" variance in deviation-from-theory (residual = %.1f%%).\n",
             100 * at4m[["Sum Sq"]][rim] / ss4m)
    }

    # Hudson FST is a ratio of within/between diversity, so the exclusion that costs
    # pi/dxy double-digit percentages at high theta costs FST ~0.3% (numerator and
    # denominator move alike and cancel). each estimator vs its own `theoretical`
    # (biallelic -> infinite-sites, multi -> finite-sites). see section 5
    fstf <- dxyf_sum4 |>
        filter(stat == "fst_hudson", estimator %in% c("new", "new_multi")) |>
        mutate(contains_E = q025 <= theoretical & q975 >= theoretical)
    emit("\n**Hudson FST.** A ratio of sums, so the biallelic downward bias largely")
    emit(" cancels between numerator and denominator; each estimator tracks its own")
    emit(" expectation across the sweep:\n")
    for (est in c("new", "new_multi")) {
        x <- fstf |> filter(estimator == est)
        if (nrow(x) == 0) next
        lab <- if (est == "new") "biallelic (vs infinite-sites E[FST] = 0.237)" else
                                 "multiallelic-aware (vs finite-sites E[FST](theta))"
        emit("\n- %s: max |bias| = %.2f%% over %d cells; across-replicate 95%% interval contains E[FST] in %d / %d cells",
             lab, max(abs(x$bias_pct)), nrow(x), sum(x$contains_E), nrow(x))
    }
    emit("\n")

    # Hudson FST factorial ANOVA: is deviation from each estimator's own E[FST]
    # related to estimator, theta, ploidy? two real FST estimators now: before the
    # 2026-07 fix pixy's FST path re-filtered to biallelic regardless of
    # --include_multiallelic_snps, so both columns held the biallelic estimand; as of
    # 02d6d91 `new_multi` is a real multiallelic FST across every allele column.
    # rel_dev vs the finite-sites E for both estimators (matching pi/dxy and Figure 4),
    # so the estimator term means "cost of discarding multiallelic sites". section 5
    # runs each vs its own target. per-replicate FST = pooled ratio-of-sums
    # (sum num / sum den over the rep's windows); averaging per-window ratios is
    # Jensen-biased downward
    fst_rep <- map_dfr(names(theta_ploidy_files), function(k) {
        map_dfr(names(theta_codes4), function(tc) {
            d <- read_arm(paste0("dxy_", theta_ploidy_files[k], "_2pop_theta", tc))
            if (is.null(d)) return(NULL)
            map_dfr(c("new", "new_multi"), function(est) {
                nc <- paste0("fst_hudson_num_", est)
                dc <- paste0("fst_hudson_den_", est)
                if (!all(c(nc, dc) %in% names(d))) return(NULL)
                d |>
                    select(replicate, num = all_of(nc), den = all_of(dc)) |>
                    filter(is.finite(num), is.finite(den)) |>
                    group_by(replicate) |>
                    summarise(value = sum(num) / sum(den), .groups = "drop") |>
                    mutate(ploidy = theta_ploidy_n[k], theta = unname(theta_codes4[tc]),
                           estimator = est)
            })
        })
    })
    if (nrow(fst_rep)) {
        # one expectation per theta (finite-sites) for both estimators, matching
        # sweep_rel() and Figure 4. see the note at E_fst_v
        fst_rep <- fst_rep |>
            mutate(theoretical = unname(E_fst_v[sprintf("%.3f", theta)]))
        # a missing lookup would silently NA every row and empty the model
        stopifnot(!any(is.na(fst_rep$theoretical)))
        fst_rep <- fst_rep |>
            mutate(rel_dev = 100 * (value - theoretical) / theoretical) |>
            filter(is.finite(rel_dev)) |>
            mutate(estimator_f = factor(estimator, levels = c("new", "new_multi")),
                   ploidy_f = factor(ploidy), theta_f = factor(theta))
        aovf <- aov(rel_dev ~ estimator_f * ploidy_f * theta_f, data = fst_rep)
        atf <- summary(aovf)[[1]]
        ssf <- sum(atf[["Sum Sq"]]); tnf <- trimws(rownames(atf))
        pnf <- gsub("estimator_f", "estimator",
                    gsub("ploidy_f", "ploidy",
                         gsub("theta_f", "theta", gsub(":", " x ", tnf))))
        emit("\n**Hudson FST - factorial ANOVA** (relative deviation from the finite-sites")
        emit(" E[FST] (%%) ~ estimator x ploidy x theta, all factors; both estimators judged")
        emit(" against the same expectation, as for pi and dxy above and as plotted in")
        emit(" Figure 4; per-replicate FST = pooled ratio-of-sums; N = %d replicate",
             nrow(fst_rep))
        emit(" estimates).\n")
        emit("\n| term | df | F | p | %% of total SS |")
        emit("\n|---|---|---|---|---|")
        for (i in seq_along(tnf)) {
            if (pnf[i] == "Residuals") next
            emit("\n| %s | %d | %.2f | %s | %.2f%% |",
                 pnf[i], atf[["Df"]][i], atf[["F value"]][i],
                 format.pval(atf[["Pr(>F)"]][i], digits = 2), 100 * atf[["Sum Sq"]][i] / ssf)
        }
        rif <- length(tnf)
        emit("\n| residual | %d | | | %.2f%% |\n", atf[["Df"]][rif], 100 * atf[["Sum Sq"]][rif] / ssf)
        for (est in c("new", "new_multi")) {
            x <- fst_rep |> filter(estimator == est)
            if (nrow(x) == 0) next
            cx <- ci(x$rel_dev)
            lab <- if (est == "new") "biallelic" else "multiallelic-aware"
            emit("\n- %s: pooled relative bias %+.3f%% [%+.3f%%, %+.3f%%]",
                 lab, cx$mean, cx$lo, cx$hi)
        }
        emit("\n\nNB these pooled biases are the mean over replicates of each replicate's")
        emit(" FST ratio, matching the ANOVA's unit of analysis; that is a mean-of-ratios")
        emit(" and so sits slightly below the ratio-of-sums figures reported per cell")
        emit(" (Jensen). Both estimators are affected alike, so the comparison between them")
        emit(" is fair. Note the biallelic bias here is POSITIVE: measured against the")
        emit(" finite-sites estimand it sits high, because it is recovering the coalescent")
        emit(" FST (see section 5) -- it is not a broken estimator, it is a different one.\n")
        nsig_f <- sum(atf[["Pr(>F)"]][-rif] > 0.05, na.rm = TRUE)
        emit("\n%d / %d terms are non-significant at alpha = 0.05; the model explains %.2f%%",
             nsig_f, rif - 1, 100 * (ssf - atf[["Sum Sq"]][rif]) / ssf)
        emit(" of the variance in deviation-from-theory (residual, i.e. replicate noise =")
        emit(" %.1f%%).", 100 * atf[["Sum Sq"]][rif] / ssf)
        emit(" The estimator term is the cost of discarding multiallelic sites, measured")
        emit(" against the finite-sites estimand -- the same quantity the pi and dxy")
        emit(" analyses above report. Its effect size is what matters here: compare the")
        emit(" FST estimator term below with the pi and dxy ones above, where the same")
        emit(" exclusion costs double-digit percentages.\n")
    }
}

##########
# write out
##########
dir.create("figs", showWarnings = FALSE)
writeLines(out, "figs/inline_stats.md")
cat("Wrote figs/inline_stats.md\n")
